---
- name: Creating the users.
  user:
    name: "{{ sname }}"
    password: "{{ 'm0nk3y' | password_hash('sha512') }}"
    comment: "{{ sfull }}"
    shell: /bin/bash
    group: wheel
    groups: wheel
    home: /home/{{ sname }}
