---
- name: Creating th users.
  user:
    name: "{{ sname }}"
    password: "{{ 'ambr0s1a' | password_hash('sha512') }}"
    comment: "{{ sfull }}"
    shell: /bin/bash
    group: wheel
    groups: wheel
    home: /home/{{ sname }}
